import requests

# Define the URL of the Express API endpoint
url = 'http://localhost:3001/prompt'

# Prepare the data to be sent in the POST request
data = {
    "text": "What is your name?"  # The question generated by Python
}

# Send a POST request to the Express API to get the question
response = requests.post(url, json=data)

# Check if the request was successful
if response.status_code == 200:
    result = response.json()
    print(f'Question from Express API: {result["question"]}')
    
    # Now we wait for the answer, which will be submitted by the frontend and sent back to Express
    # The answer is returned as part of the response when the frontend submits it
else:
    print(f'Failed to get question: {response.status_code}')

